# Generated by Django 4.0.6 on 2022-07-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employees_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='addres',
            new_name='address',
        ),
    ]
